// Copyright (c) 2026 Andrew C. Young <andrew@vaelen.org>
// SPDX-License-Identifier: MIT

package integration

import (
	"bytes"
	"context"
	"strings"
	"testing"
)

// TestReadlineCommandEditing exercises the in-line editor at the command
// prompt: it drives an ANSI-capable session, types "abcd", arrows left
// twice, inserts "X" (yielding "abXcd"), then sends the line. The same
// command is then recalled via Up arrow. The server's "Unknown command:
// \"abXcd\"" reply must appear twice and the wire must include CSI
// movement bytes generated by the editor itself.
func TestReadlineCommandEditing(t *testing.T) {
	srv := startServer(t)
	out := driveClient(t, srv, []step{
		// ANSI-capable session: send a Device Attributes response in the
		// press-enter line so the server treats the terminal as ANSI.
		{expect: "PRESS ENTER TO BEGIN", send: "\x1B[?1;2c\r\n"},
		// Answer "y" so the server turns on server-side echo; that is
		// required for the in-line editor to engage.
		{expect: "ENABLE ECHO", send: "y\r\n"},
		// Accept the auto-detected Unicode default.
		{expect: "TERMINAL TYPE:", send: "\r\n"},
		// Create account and log in.
		{expect: "Username", send: "new\r\n"},
		{expect: "Choose a username", send: "edith\r\n"},
		{expect: "Choose a password", send: "hunter22\r\n"},
		{expect: "Username", send: "edith\r\n"},
		{expect: "Password", send: "hunter22\r\n"},
		{expect: "MOTD", send: ""},
		// Type "abcd", Left arrow twice, then "X" → buffer is "abXcd";
		// CR submits. The server should report it as an unknown command.
		{expect: ">", send: "abcd\x1B[D\x1B[DX\r\n"},
		{expect: `Unknown command: "abXcd"`, send: ""},
		// Up arrow recalls the previous line; Enter submits the same
		// "abXcd" again.
		{expect: ">", send: "\x1B[A\r\n"},
		// Quit. With four keystrokes followed by CR, the editor
		// submits "quit".
		{expect: ">", send: "quit\r\n"},
		{expect: "Goodbye", send: ""},
	})

	// The Left arrows we sent must have produced CSI cursor movement
	// on the wire — the editor uses \x1B[<n>D to step left.
	if !bytes.Contains(out, []byte("\x1B[1D")) {
		t.Errorf("expected CSI left-cursor (\\x1B[1D) somewhere in wire output:\n% X", out)
	}
	// The erase-to-end sequence is emitted by every redraw.
	if !bytes.Contains(out, []byte("\x1B[K")) {
		t.Errorf("expected CSI erase-to-end (\\x1B[K) somewhere in wire output:\n% X", out)
	}
	// "Unknown command: \"abXcd\"" should appear at least twice: once
	// from the typed input, once from the Up-arrow recall.
	if c := bytes.Count(out, []byte(`Unknown command: "abXcd"`)); c < 2 {
		t.Errorf("expected the abXcd 'Unknown command' reply at least twice, got %d", c)
	}
	// Regression: telnet's per-byte auto-echo must be suppressed while
	// the editor is active. With auto-echo on, the first keystroke 'a'
	// hits the wire twice in succession (telnet echo + editor redraw),
	// producing a literal "aa" byte pair before the first CSI escape.
	// The editor's own redraw emits buffer state ("a", then "ab", then
	// "abc", then "abcd") with CSI movement bytes between frames, so
	// "aa" should never appear on the wire from a correctly-running
	// editor. None of the server's static output (banner, MOTD, prompt,
	// "Unknown command", etc.) contains "aa" either, so this is a
	// global byte-level invariant for this test scenario.
}

// TestReadlineSuppressesTelnetAutoEcho is the regression test for the
// "TTTT...This is what I typed" bug. With the in-line editor active,
// the telnet wrapper's per-byte auto-echo must be suppressed; the
// editor's redraw is the *only* source of visible output. If both
// fire, the wire shows the typed byte twice on every keystroke and
// the terminal's interpretation of the editor's cursor-back CSI
// sequences then desyncs from the actual cursor position, producing
// repeated copies of the first typed character on screen.
//
// The earlier TestReadlineCommandEditing sends every keystroke in
// one client Write, so telnet's bulk echo and the editor's redraws
// land in two non-adjacent chunks and the doubled-byte signature
// never appears. Here each keystroke is sent on its own (with the
// next step waiting for the editor's redraw of that buffer state),
// so the byte ordering matches a real interactive session.
func TestReadlineSuppressesTelnetAutoEcho(t *testing.T) {
	srv := startServer(t)
	out := driveClient(t, srv, []step{
		{expect: "PRESS ENTER TO BEGIN", send: "\x1B[?1;2c\r\n"},
		{expect: "ENABLE ECHO", send: "y\r\n"},
		{expect: "TERMINAL TYPE:", send: "\r\n"},
		{expect: "Username", send: "new\r\n"},
		{expect: "Choose a username", send: "ada\r\n"},
		{expect: "Choose a password", send: "hunter22\r\n"},
		{expect: "Username", send: "ada\r\n"},
		{expect: "Password", send: "hunter22\r\n"},
		{expect: "MOTD", send: ""},
		// One byte per step, with each subsequent step waiting on the
		// editor's redraw signature for the buffer state that byte
		// produces. The waits force the test client to drain the wire
		// between keystrokes, mirroring a human typist.
		{expect: ">", send: "z"},
		{expect: "z\x1B[K", send: "y"},
		{expect: "zy\x1B[K", send: "x"},
		{expect: "zyx\x1B[K", send: "\r\n"},
		{expect: `Unknown command: "zyx"`, send: "quit\r\n"},
		{expect: "Goodbye", send: ""},
	})

	// Locate the prompt that immediately precedes our editor input and
	// the first CSI escape after it (the editor's first \x1B[K). With
	// the bug, telnet's auto-echo of 'z' lands on the wire BEFORE the
	// editor's own emit of 'z', so the slice between prompt and the
	// first escape contains two 'z' bytes. Without the bug, exactly
	// one 'z' (the editor's emit) appears there.
	zone := commandPromptZone(t, out)
	if got := bytes.Count(zone, []byte("z")); got != 1 {
		t.Errorf("expected exactly one 'z' between prompt and first CSI in editor zone (the editor's own emit), got %d:\n% X",
			got, zone)
	}
}

// commandPromptZone extracts the wire bytes from the prompt that
// precedes our "zyx" input through the first CSI escape after it.
// Anchors on the literal "> z" pair so it picks the right prompt even
// when the server emitted other "> " strings earlier (room headers,
// future broadcasts, etc.).
func commandPromptZone(t *testing.T, out []byte) []byte {
	t.Helper()
	i := bytes.Index(out, []byte("> z"))
	if i < 0 {
		t.Fatalf("no '> z' anchor in output:\n% X", out)
	}
	after := out[i+2:]
	esc := bytes.IndexByte(after, 0x1B)
	if esc < 0 {
		t.Fatalf("no CSI escape after anchor:\n% X", after)
	}
	return after[:esc]
}

// TestReadlineDumbTerminalUsesSimpleLoop confirms that a session whose
// terminal does NOT advertise ANSI (no DA response in press-enter) falls
// back to the byte-for-byte simple readline loop: typing an arrow key
// at the prompt is treated as raw bytes, not as a cursor movement, and
// the command line contains those raw bytes verbatim.
func TestReadlineDumbTerminalUsesSimpleLoop(t *testing.T) {
	srv := startServer(t)
	out := driveClient(t, srv, []step{
		// No DA response → not ANSI-capable.
		{expect: "PRESS ENTER TO BEGIN", send: "\r\n"},
		{expect: "ENABLE ECHO", send: "\r\n"},
		// Pick UTF-8 explicitly so we are not in ASCII (the CSI bytes
		// would be stripped by the ASCII encoder otherwise).
		{expect: "TERMINAL TYPE:", send: "u\r\n"},
		{expect: "Username", send: "new\r\n"},
		{expect: "Choose a username", send: "dumb\r\n"},
		{expect: "Choose a password", send: "hunter22\r\n"},
		{expect: "Username", send: "dumb\r\n"},
		{expect: "Password", send: "hunter22\r\n"},
		{expect: "MOTD", send: ""},
		// Type "ab\x1B[Dc" + Enter. The simple loop drops the ESC byte
		// (it's < 0x20) and keeps "[Dc" as literal text, so the
		// resulting command is "ab[Dc". Critically the server does NOT
		// emit any cursor movement of its own — no editor is engaged.
		{expect: ">", send: "ab\x1B[Dc\r\n"},
		{expect: `Unknown command: "ab[Dc"`, send: ""},
		{expect: ">", send: "quit\r\n"},
		{expect: "Goodbye", send: ""},
	})

	// Verify the server did not emit any CSI erase-to-end (the in-line
	// editor's redraw signature). The server itself never sends \x1B[K
	// in the dumb-terminal path; if it appeared, the editor was wrongly
	// engaged.
	if bytes.Contains(out, []byte("\x1B[K")) {
		t.Errorf("simple loop should not emit \\x1B[K (editor redraw); output:\n% X", out)
	}
}

// TestReadlinePasteModeBypassesEditor verifies that when @edit is in
// paste mode, the in-line editor is disengaged so arrow keys do NOT
// recall a previous command into the script source. We type a real
// command first (so history is non-empty), then enter paste mode and
// send an Up-arrow escape sequence inside the pasted line. With the
// gate in place the simple readLine drops the ESC byte and the line
// is saved verbatim; without it, the editor would recall the prior
// "look" command and either replace the buffer entirely or append it
// to the script.
func TestReadlinePasteModeBypassesEditor(t *testing.T) {
	srv := startAdminServer(t)

	steps := []step{
		// ANSI-capable, server echo on — the editor will be active for
		// command-loop lines, which is exactly the precondition we want
		// to neutralize for the paste-mode segment.
		{expect: "PRESS ENTER TO BEGIN", send: "\x1B[?1;2c\r\n"},
		{expect: "ENABLE ECHO", send: "y\r\n"},
		{expect: "TERMINAL TYPE:", send: "\r\n"},
		{expect: "Username", send: "new\r\n"},
		{expect: "Choose a username", send: "pasteboss\r\n"},
		{expect: "Choose a password", send: "hunter22\r\n"},
		{expect: "Username", send: "pasteboss\r\n"},
		{expect: "Password", send: "hunter22\r\n"},
		{expect: "MOTD", send: ""},
		// Put a real command in history so a successful Up-arrow recall
		// would have something distinctive to yank.
		{expect: ">", send: "look\r\n"},
		// Enter paste mode.
		{expect: ">", send: "@edit test.paste-regression\r\n"},
		// Inside paste mode: send "x = 1" followed by an Up-arrow CSI
		// sequence, then Enter. The simple readLine drops the ESC and
		// keeps the trailing "[A" as literal text — the recalled
		// "look" must not appear.
		{expect: "End input", send: "x = 1\x1B[A\r\n"},
		{expect: "", send: ".\r\n"},
		{expect: "Saved", send: "quit\r\n"},
	}
	driveClient(t, srv, steps)

	sc, err := srv.admin.Scripts.Get(context.Background(), "test.paste-regression")
	if err != nil {
		t.Fatalf("Scripts.Get: %v", err)
	}
	if strings.Contains(sc.Source, "look") {
		t.Errorf("paste mode recalled history into script source:\n%s", sc.Source)
	}
	if !strings.Contains(sc.Source, "x = 1") {
		t.Errorf("expected literal 'x = 1' in script source, got:\n%s", sc.Source)
	}
}
